### ISSUE TITLE
能否去掉package.json中的"type": "module"

### ISSUE THREAD

**Issue by ColourfulU** [Autumn-one/a-calc-old#11]
这个库使用起来很优雅，我很喜欢，但我在node环境中使用require语法导入时，方法没有类型提示
![image](https://github.com/user-attachments/assets/d410c8d9-263c-4fd1-87ae-30250486f95a)

然后我换成import语法导入，又提示我“当前文件是 CommonJS 模块，其导入将生成“require”调用；但是，引用的文件是 ECMAScript 模块，它不能使用“require”进行导入。请考虑改为编写动态“import("a-calc")”调用”
![image](https://github.com/user-attachments/assets/fb146977-7739-4114-b219-14a25ceab85b)

如果可以，能否将package.json中的"type": "module"去掉

**Comment by Autumn-one** [comment]
commonjs项目可以使用 "a-calc/cjs" 来引入，你也可以打包一份可复现的最简化项目代码。

**Comment by ColourfulU** [comment]
很高兴能收到你的回复，我尝试了使用 "a-calc/cjs" 来引入，但是问题依然存在
![image](https://github.com/user-attachments/assets/86118987-d919-4687-8f11-740d2021497d)

这是一个简化代码，麻烦帮忙看看：[a-calc-mini.zip](https://github.com/user-attachments/files/18001997/a-calc-mini.zip)

还有个小建议，不知道大神方不方便处理一下，就是带单位计算的时候，如果有参数不是字符串类型，会报错：
`calc('m / c | !u', { m: '1000%', c: 100, _unit: true })`

**Comment by ColourfulU** [comment]
> 很高兴能收到你的回复，我尝试了使用 "a-calc/cjs" 来引入，但是问题依然存在 ![image](https://private-user-images.githubusercontent.com/65552891/392205462-86118987-d919-4687-8f11-740d2021497d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyODI4MjMsIm5iZiI6MTczMzI4MjUyMywicGF0aCI6Ii82NTU1Mjg5MS8zOTIyMDU0NjItODYxMTg5ODctZDkxOS00Njg3LThmMTEtNzQwZDIwMjE0OTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDAzMjIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNjQxMjA5YTNmODBlMDE4NzkyYWM5YmMxZjdkNThiYTVhYzY1MDcwMDUwNWZhNjQ2ZTU4MzUxNTllYzRiYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.aW8opEQ_2Lp-NUomkEnrc8G6ZwQ10CKou-Cs5Iz5xIY)
> 
> 这是一个简化代码，麻烦帮忙看看：[a-calc-mini.zip](https://github.com/user-attachments/files/18001997/a-calc-mini.zip)
> 
> 还有个小建议，不知道大神方不方便处理一下，就是带单位计算的时候，如果有参数不是字符串类型，会报错： `calc('m / c | !u', { m: '1000%', c: 100, _unit: true })`

不好意思，代码里脚本执行文件路径写的有点问题，"serve": "tsx watch src/main.ts" 应改为 "serve": "tsx watch index.ts",

**Comment by Autumn-one** [comment]
单位计算的问题下个版本会做兼容处理，你目前这个项目是一个纯node项目是吧？也就是项目整体都用commonjs规范，但是目前在commonjs规范下确实没有很好的类型提示

**Comment by ColourfulU** [comment]
> 单位计算的问题下个版本会做兼容处理，你目前这个项目是一个纯node项目是吧？也就是项目整体都用commonjs规范，但是目前在commonjs规范下确实没有很好的类型提示

是的，我的项目是一个纯node项目，我在tsconfig.json中配置了"esModuleInterop": true,  允许使用es模块的import导入语法，导入其它的包没问题，也有类型提示，我尝试修改node_modules中a-calc包的package.json文件，去掉其中的type: "module"，使用import语法也不会报错了，就是不知道去掉这个属性，对您的项目有没有影响

**Comment by Autumn-one** [comment]
2.2.14版本已解决此问题

**Comment by ColourfulU** [comment]
> 2.2.14版本已解决此问题

作者大大牛批，强烈推荐给小伙伴了

**Comment by ColourfulU** [comment]
非常感激您抽出宝贵时间回答我的问题，衷心感谢您的支持和帮助！🙏，谢谢！🙌
