### ISSUE TITLE
数字取整

### ISSUE THREAD

**Issue by MangMax** [Autumn-one/a-calc-old#2]
请问如何取整数，我尝试设置小数位为0但是没有效果，设置0以上是没有问题的

**Comment by Autumn-one** [comment]
> 请问如何取整数，我尝试设置小数位为0但是没有效果，设置0以上是没有问题的

发示例代码看看

**Comment by MangMax** [comment]
![image](https://github.com/Autumn-one/a-calc-old/assets/68525017/f21b733a-e695-4f15-86de-b94d4413ebad)

**Comment by Autumn-one** [comment]
> ![image](https://private-user-images.githubusercontent.com/68525017/310014051-f21b733a-e695-4f15-86de-b94d4413ebad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MjI1MTMsIm5iZiI6MTcwOTYyMjIxMywicGF0aCI6Ii82ODUyNTAxNy8zMTAwMTQwNTEtZjIxYjczM2EtZTY5NS00ZjE1LTg2ZGUtYjk0ZDQ0MTNlYmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDA3MDMzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMDFlNDNlNmY4YTQ4YzQ0NmNmNjg5NjRiOWRkMzFlMWFkNWZmNjUyYTNmNGM2NDk0MjAyNTIyMjVjMWU3ZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bPJiZns0TTkksXqvs1qzAKta7AgeBmbu424_2y4moUM)

这是一个bug，把=b写成=0是正确的结果，对于这种情况缺少测试用例，今天发个新版修复一下

**Comment by MangMax** [comment]
好的，谢谢！
