### ISSUE TITLE
ts中使用类型丢失

### ISSUE THREAD

**Issue by wgh4318** [Autumn-one/a-calc-old#5]
我在.vue文件使用没问题，但是写hooks的时候在.ts使用发现类型没了

```javascript
import { calc } from "a-calc";

const [a, b] = [0.1, 0.2];

const c = calc("a+b", { a, b });

console.log("c :>> ", c);
```

分别在`.vue`和'.ts'写上面代码 vue文件里没问题，ts文件就会报下面错误

![image](https://github.com/Autumn-one/a-calc-old/assets/76714819/c7f09995-6858-4610-b94c-8c8b0babc591)

**Comment by Autumn-one** [comment]
> 我在.vue文件使用没问题，但是写hooks的时候在.ts使用发现类型没了
> 
> ```js
> import { calc } from "a-calc";
> 
> const [a, b] = [0.1, 0.2];
> 
> const c = calc("a+b", { a, b });
> 
> console.log("c :>> ", c);
> ```
> 
> 分别在`.vue`和'.ts'写上面代码 vue文件里没问题，ts文件就会报下面错误
> 
> ![image](https://private-user-images.githubusercontent.com/76714819/343613982-c7f09995-6858-4610-b94c-8c8b0babc591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDIxMDcsIm5iZiI6MTcxOTUwMTgwNywicGF0aCI6Ii83NjcxNDgxOS8zNDM2MTM5ODItYzdmMDk5OTUtNjg1OC00NjEwLWI5NGMtOGM4YjBiYWJjNTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE1MjMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViY2VmZjcwYTMyZDlhMmE5NDMzYWIyNmM2ZmZkOTQ0Njc4YTdkMTE2ZDQxNTMxYmQyZDUyYTIyODc0MzdlZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5ECMb0XcaQLBzc0bySTI0PvNXssmW9t8wLgxFp_1spE)

这个问题我无法再最新的版本中复现，你可能需要提供更多的信息，例如：使用的版本，引入方式等。或者检查自己的项目配置环境。

**Comment by wgh4318** [comment]
已解决，是由于ts版本过低，tsconfig没有引用类型
