### ISSUE TITLE
calc在数组reduce中无法获取到value

### ISSUE THREAD

**Issue by zhengju1893** [Autumn-one/a-calc-old#6]
`
![image](https://github.com/Autumn-one/a-calc-old/assets/23161548/cb143831-b36f-4dbb-a7cd-1906de0e692d)
`

报错信息
![image](https://github.com/Autumn-one/a-calc-old/assets/23161548/128dc771-082c-4595-8be0-0a07df2f6187)
报错代码位置
![image](https://github.com/Autumn-one/a-calc-old/assets/23161548/b4b14651-6a24-4f84-82fa-52d006efe23a)

**Comment by Autumn-one** [comment]
看起来就是普通的业务逻辑错误，代码怎么写的？

**Comment by zhengju1893** [comment]
抱歉，是我的原因，我的语法写错了。。。。
修饰符忘了使用 | 符号了。。。。
