### ISSUE TITLE
移动端运行不兼容报错

### ISSUE THREAD

**Issue by wgh4318** [Autumn-one/a-calc-old#8]

**Comment by Autumn-one** [comment]
你这样提issues我怎么排查？

**Comment by wgh4318** [comment]
使用的是HBuildeX打包的uniapp，真机调试，使用`calc('0.1 +0.2', {__error: 0})`,没显示

**Comment by Autumn-one** [comment]
`calc('0.1 +0.2', {__error: 0})` 是 `_error` 不是 `__error`， 我使用 uniapp 创建了一个 uni-ui 项目并且使用使用浏览器运行模式无法重现问题，至于真机调试我无法成功在我的设备上成功运行，根据目前的信息我无法确切的定位问题，你可能需要结合项目报错信息自己排查解决。

**Comment by wgh4318** [comment]
浏览器模式下是没问题的，但真机调试或者说在模拟器上运行就会没效果
